return {
	pde = {
		-- ai = false,
		angular = true,
		cpp = false,
		csharp = true,
		copilot = false,
		docker = true,
		elixir = true,
		flutter = false,
		go = false,
		html = true,
		java = false,
		json = true,
		julia = true,
		jupyter = true,
		kotlin = true,
		lua = true,
		python = true,
		r = true,
		react = true,
		ruby = true,
		rust = true,
		scala = true,
		solidity = false,
		svelte = true,
		tailwind = false,
		terraform = true,
		typescript = true,
		vuejs = true,
	},
}
